version: "3.3"

services:
  app:
    build: .
    container_name: app-dev
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
