version: "3.3"

services:
  app:
    build: .
    image: app-dev
    container_name: node-dev5
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-data:
